application:
  name: "exasure-address-api"
  version: "1.0.0"
api:
    id: ""

http:
    port: "8081"
    secure.port: "8091"
    readTimeout: "30000"
    connectionTimeOut: "40000"

https:
    port: "8082"
    secure.port: "8092"
    path: "/api/*"

reconnection:
    frequecy: "2000"
    attempts: "2"


cloudhub:
  exasure-address-sapi:
    hostName: "https://exasure-address-sapi-1pnc4b.5sc6y6-3.usa-e2.cloudhub.io"
    path:
      getAddressAutocomplete: "/api/address/autocomplete"
  exasure-dmv-sapi:
    hostName: "https://exasure-dmv-sapi-1pnc4b.5sc6y6-3.usa-e2.cloudhub.io"
    path:
      postLicenseVerification: "/api/license/verification"
  